### PR TITLE
dave stone play services lab incomplete

### PR DESCRIPTION
**Pull request by davidhstone**

### CODE REVIEW

**Comment by charlesdrews** [comment]
You have the right start, but there's not quite enough here for me to mark this complete. We'll have solution code posted soon.

**Comment by davidhstone** [comment]
How long do I have to modify it? Also, how many points am I getting for it
as is vs. how many points it's worth max?

**Comment by charlesdrews** [comment]
This wasn't one of the labs with detailed feedback, so there's no rubric or
points, but what I was really looking for was at least an attempt to show
the user's location on the map, as opposed to the default code that shows
Sydney, Australia. It just didn't look like there was very much there
beyond the auto-generated code you get when you create a maps activity.

Regarding timing, Alan hasn't posted the solution for this one yet, so it's
still OK to resubmit. I'm not sure if he will post tomorrow or next week.

**Comment by davidhstone** [comment]
Ah... yup... for some reason I thought you were talking about the media
player lab. Yup... that's exactly what I did for this lab. Was so burnt out
that night I'm surprised I got anything turned in. ::sad lol::

**Pull request closed without merging**
